### ISSUE TITLE
maxSize argument exceeds QByteArray size limit

### ISSUE THREAD

**Issue by coooooooorey** [Skycoder42/QtApng#10]
I built the qapng.dll from the source. 
Env: msvc 2017  32bit . Qt5.15.0 beta and Qt5.14.0.

But when I am trying to read a  apng. I got
QIODevice::read (QFile, "...\examples\apng\sample\sample.apng"): maxSize argument exceeds QByteArray size limit

Is there any way to solve this?

Thanks~

**Comment by Skycoder42** [comment]
That's a very strange error. Apparently, it fails to read a file. If that is the case, then your Qt installation is broken.

Please try the following, and check if the same error appears:
```
QFile file("...\examples\apng\sample\sample.apng");
qDebug() << file.open(QIODevice::ReadOnly);
qDebug() << file.readAll().size();
qDebug() << file.errorString();
```

Theoretically, you should get
```
true
198000 (or a number of similar magnitude)
""
```

**Comment by coooooooorey** [comment]
![image](https://user-images.githubusercontent.com/3081374/75941155-e9aba880-5ec9-11ea-93b2-b248816d046f.png)


My Qt5.15 beta is from online-installer.
5.14 is from offline-installer.
My other apps are working fine. So I guess it's not about the Qt installation.

**Comment by coooooooorey** [comment]
actually, I tried to use the dll from https://github.com/Skycoder42/QtApng/releases
it's the same.

**Comment by ghost** [comment]
I can confirm the same issue with both 5.14 and 5.15. This does not affect Qt versions 5.13.2 or earlier.

**Comment by Skycoder42** [comment]
I can reproduce this issue on linux as well. Here however, this only happens when loading the apng as QPixmap instead of QMovie - can you confirm this?

**Comment by Skycoder42** [comment]
Please try to explicity specify "apng" as image type. Because if I do this on my system, it suddenly works - which makes absolutely no sense...

**Comment by Skycoder42** [comment]
I found the problem. For whatever reason Qt resets the device between "canRead" and "read". The handler was adjusted to correctly handle such cases

**Comment by coooooooorey** [comment]
thanks~

But it seems like the qmovie  is not showing the correct image.
