### ISSUE TITLE
Transparency problem?

### ISSUE THREAD

**Issue by MD-ThorErik** [Skycoder42/QtApng#4]
It seems apngs with transparent background are not rendered properly. The moving area is updated but the unmoving transparent area is shown in a black color, as can be observed in [this example file](https://upload.wikimedia.org/wikipedia/commons/1/14/Animated_PNG_example_bouncing_beach_ball.png).

**Comment by Skycoder42** [comment]
I can confirm. Playing it in "stop-motion" reveals that the first frame is displayed correctly, but for all subsequent frames the described behaviour occurs.

**Comment by Skycoder42** [comment]
Simple error, I messed up filling the background by not setting the alpha channel to 0. Tested with your image and should work now.
