### ISSUE TITLE
Incorrect output of nextImageDelay()

### ISSUE THREAD

**Issue by oldmud0** [Skycoder42/QtApng#7]
`nextImageDelay()` is supposed to return "the number of milliseconds to wait until reading the next image" ([docs](http://doc.qt.io/qt-5/qimageiohandler.html#nextImageDelay)), so that it works with QMovie.

However, one of our developers is reporting that instead, ApngImageHandler is returning the delay of the next frame and the next next frame, instead of the delay of the current frame and the next frame.

I'll follow this issue up with a minimal example to help you reproduce the issue.

**Comment by Skycoder42** [comment]
This definitely sounds like a bug. I never tested the library with with variable frame delays - so it's very possible I messed that up. An example would be really useful, so thanks in advance. Especially an APNG-File that has variable frame delays would be most helpful to fix this problem.

**Comment by oldmud0** [comment]
Try this file:
![anormal](https://user-images.githubusercontent.com/5247009/51573975-58b67100-1e71-11e9-9990-af1650d4e375.png)

**Comment by Skycoder42** [comment]
I was able to locate the origin of that problem, and start working on a fix now. It seems I wrongfully incremented an internal counter to early, leading to this problem.

**Comment by Skycoder42** [comment]
One more question: I would like to add the APNG-File you posted to the test cases to have this specific situation tested. Can you specify under which license/from which source this image is?

**Comment by oldmud0** [comment]
It's Calisto Yew ripped from Ace Attorney. I was just too lazy to make an original test file at the time. I'll supply you with another one you can use.

**Comment by Skycoder42** [comment]
Thank you very much!

**Comment by Skycoder42** [comment]
I have created such an image myself now, using online tools and a license-free base image

**Comment by oldmud0** [comment]
Yikes, how did I forget. Sorry.

**Comment by Skycoder42** [comment]
No problem. It was easier than I expected it to be, so no reason why I could not do it myself
